name: Build and Release net-snmp

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - MSVCDYNAMIC64
          - MSVCSTATIC64
          - INSTALLER

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout net-snmp repository
      uses: actions/checkout@v4
      with:
        repository: net-snmp/net-snmp
        path: net-snmp

    - name: Setup MSVC and environment variables
      shell: cmd  # Use cmd for vcvars64.bat
      run: |
        set VCVARSPATH=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build
        if not exist "%VCVARSPATH%" (
          echo "Error: MSVC vcvars64.bat not found. Visual Studio 2022 Enterprise is required."
          exit /b 1
        )
        call "%VCVARSPATH%\vcvars64.bat"
        set PATH=C:\Perl64\bin;%PATH%
        set OPENSSLDIR=C:\OpenSSL-Win64
        set PATH=%PATH%;C:\cygwin64\bin
      continue-on-error: true

    - name: Install OpenSSL dependency
      shell: powershell  # Switch to PowerShell for Chocolatey commands
      run: |
        # Install OpenSSL
        choco install openssl -y
        # Import Chocolatey profile module and refresh environment
        Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        Update-SessionEnvironment
        # Verify OpenSSL is in PATH
        Write-Output "OpenSSL version:"
        openssl version
      continue-on-error: true

    - name: Check for existing Perl installation
      shell: powershell
      run: |
        if (Test-Path -Path "C:\Perl64") {
          Write-Output "Existing Perl installation found at C:\Perl64. Attempting to uninstall..."
          Get-ChildItem -Path "C:\Perl64" -Recurse
          exit 1  # Fail the step to force review; remove if uninstall logic is added
        } else {
          Write-Output "No existing Perl installation detected."
        }
      continue-on-error: true

    - name: Install ActivePerl with detailed logging
      shell: powershell
      run: |
        # Install ActivePerl
        choco install activeperl --install-arguments "'/quiet PERL_PATH=Yes PERL_EXT=Yes /l*v c:\ActivePerl_msi_install.log'" -y
        # Refresh environment after installation
        Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
        Update-SessionEnvironment
      continue-on-error: true  # Allow continuation to upload logs even if this fails

    - name: Upload ActivePerl MSI log
      if: always()
      shell: powershell
      run: |
        New-Item -ItemType Directory -Path "artifacts" -Force
        if (Test-Path -Path "c:\ActivePerl_msi_install.log") {
          Copy-Item -Path "c:\ActivePerl_msi_install.log" -Destination "artifacts\"
        } else {
          Write-Output "MSI log file not found."
        }

    - name: Upload log artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ActivePerl_msi_log
        path: artifacts/ActivePerl_msi_install.log

    - name: Verify Perl installation
      shell: cmd  # Use cmd for perl -v
      run: |
        perl -v
        if %errorlevel% neq 0 (
          echo Perl installation failed or not found in PATH.
          exit 1
        )

    - name: Build net-snmp
      shell: cmd  # Use cmd for build.bat
      run: |
        cd net-snmp
        call ci/build.bat ${{ inputs.buildType }}
        if %errorlevel% neq 0 exit /b %errorlevel%

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: net-snmp-${{ inputs.buildType }}
        path: |
          c:/usr/**/*
          !**/*.pdb
          !**/*.obj

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: net-snmp-${{ inputs.buildType }}
        path: build

    - name: Create zip file
      run: |
        cd build
        zip -r ../net-snmp-${{ inputs.buildType }}.zip ./

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MALAS_TOKEN }}
      with:
        tag_name: release-${{ github.sha }}
        release_name: Net-SNMP Build For ${{ inputs.buildType }}-${{ github.sha }}
        body: |
          Net-SNMP release build for commit ${{ github.sha }}
          Build Configuration: ${{ inputs.buildType }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MALAS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: net-snmp-${{ inputs.buildType }}.zip
        asset_name: net-snmp-${{ inputs.buildType }}.zip
        asset_content_type: application/zip