name: Build and Release net-snmp

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - MSVCDYNAMIC64
          - MSVCSTATIC64
          - INSTALLER

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout net-snmp repository
      uses: actions/checkout@v4  # Updated to latest version
      with:
        repository: net-snmp/net-snmp
        path: net-snmp

    - name: Setup MSVC and environment variables
      run: |
        cmd /c "
        set p=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build
        if exist "%p%" set "VCVARSPATH=%p%"
        set p=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build
        if exist "%p%" set "VCVARSPATH=%p%"
        call "%VCVARSPATH%\vcvars64.bat"
        set PATH=C:\Perl64\bin;%PATH%
        set OPENSSLDIR=C:\OpenSSL-Win64
        set PATH=%PATH%;C:\cygwin64\bin
        "

    - name: Install OpenSSL dependency
      run: |
        choco install openssl -y

    - name: Check for existing Perl installation
      run: |
        if exist "C:\Perl64" (
          echo "Existing Perl installation found at C:\Perl64. Attempting to uninstall..."
          dir "C:\Perl64" /s
          exit 1  # Fail the step to force review; remove this line if uninstall logic is added
        ) else (
          echo "No existing Perl installation detected."
        )

    - name: Install ActivePerl with detailed logging
      run: |
        choco install activeperl --install-arguments "'/quiet PERL_PATH=Yes PERL_EXT=Yes /l*v c:\ActivePerl_msi_install.log'" -y
      continue-on-error: true  # Allow continuation to upload logs even if this fails

    - name: Upload ActivePerl MSI log
      if: always()  # Ensures log is uploaded even if installation fails
      run: |
        mkdir -p artifacts
        if exist "c:\ActivePerl_msi_install.log" (
          copy c:\ActivePerl_msi_install.log artifacts\
        ) else (
          echo "MSI log file not found."
        )

    - name: Upload log artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ActivePerl_msi_log
        path: artifacts/ActivePerl_msi_install.log

    - name: Verify Perl installation
      run: |
        perl -v
        if %errorlevel% neq 0 (
          echo "Perl installation failed or not found in PATH."
          exit 1
        )

    - name: Build net-snmp
      run: |
        cd net-snmp
        call ci/build.bat ${{ inputs.buildType }}
        if %errorlevel% neq 0 exit /b %errorlevel%

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: net-snmp-${{ inputs.buildType }}
        path: |
          c:/usr/**/*
          !**/*.pdb
          !**/*.obj

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: net-snmp-${{ inputs.buildType }}
        path: build

    - name: Create zip file
      run: |
        cd build
        zip -r ../net-snmp-${{ inputs.buildType }}.zip ./

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MALAS_TOKEN }}
      with:
        tag_name: release-${{ github.sha }}
        release_name: Net-SNMP Build For ${{ inputs.buildType }}-${{ github.sha }}
        body: |
          Net-SNMP release build for commit ${{ github.sha }}
          Build Configuration: ${{ inputs.buildType }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MALAS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: net-snmp-${{ inputs.buildType }}.zip
        asset_name: net-snmp-${{ inputs.buildType }}.zip
        asset_content_type: application/zip