name: Build and Release UnityLive2d

name: Build and Release

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
        - Release
        - Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: zwa73/UnityLive2DExtractor-Unofficial
        path: target-repo

    - name: Apply patches
      shell: pwsh
      run: |
        Get-ChildItem "patches/unitylive2d/*.patch" | ForEach-Object {
          git apply --directory=target-repo $_.FullName
        }

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Restore NuGet packages
      run: nuget restore target-repo/UnityLive2DExtractor.sln

    - name: Build solution
      run: |
        msbuild target-repo/UnityLive2DExtractor.sln `
          /p:Configuration=${{ inputs.buildType }} `
          /p:Platform="Any CPU" `
          /p:DeployOnBuild=true `
          /p:PublishProfile=Release `
          /p:UseWPP_CopyWebApplication=true

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: UnityLive2DExtractor-${{ inputs.buildType }}
        path: |
          target-repo/**/bin/${{ inputs.buildType }}/**/*
          !**/*.pdb
          !**/*.obj

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: UnityLive2DExtractor-${{ inputs.buildType }}
        path: build

    - name: Create zip file
      run: |
        cd build
        zip -r ../UnityLive2DExtractor-${{ inputs.buildType }}.zip ./*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MALAS_TOKEN }}
      with:
        tag_name: release-${{ github.sha }}
        release_name: Release ${{ inputs.buildType }}-${{ github.sha }}
        body: |
          Release build for commit ${{ github.sha }}
          Build Configuration: ${{ inputs.buildType }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MALAS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: UnityLive2DExtractor-${{ inputs.buildType }}.zip
        asset_name: UnityLive2DExtractor-${{ inputs.buildType }}.zip
        asset_content_type: application/zip