name: Build and Release UnityLive2dExtract

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Build Configuration'
        required: true
        default: 'Release'
        type: choice
        options:
        - Release
        - Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: zwa73/UnityLive2DExtractor-Unofficial
        path: target-repo

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Apply patches
      shell: pwsh
      run: |
        Get-ChildItem "patches/unitylive2d/*.patch" | ForEach-Object {
          git apply --directory=target-repo $_.FullName
        }

    - name: Restore dependencies
      run: |
        cd target-repo
        dotnet restore UnityLive2DExtractor.sln

    - name: Build
      run: |
        cd target-repo
        dotnet build UnityLive2DExtractor.sln --configuration ${{ inputs.buildType }} --no-restore

    - name: Publish
      run: |
        cd target-repo
        dotnet publish UnityLive2DExtractor.sln --configuration ${{ inputs.buildType }} `
          --no-build `
          --framework net8.0 `
          --runtime win-x64 `
          --self-contained true `
          --output publish

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: UnityLive2DExtractor-${{ inputs.buildType }}-net8.0
        path: |
          target-repo/publish/**/*
          !**/*.pdb
          !**/*.obj

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: UnityLive2DExtractor-${{ inputs.buildType }}-net8.0
        path: build

    - name: Create zip file
      run: |
        cd build
        zip -r ../UnityLive2DExtractor-${{ inputs.buildType }}-net8.0-win-x64.zip ./*

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MALAS_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}-${{ inputs.buildType }}
        release_name: Release ${{ inputs.buildType }}-net8.0-${{ github.run_number }}
        body: |
          Release build for commit ${{ github.sha }}
          - Build Configuration: ${{ inputs.buildType }}
          - .NET Version: 8.0
          - Platform: win-x64
          - Build Date: ${{ github.event.head_commit.timestamp }}
          - Built by: ${{ github.actor }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MALAS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: UnityLive2DExtractor-${{ inputs.buildType }}-net8.0-win-x64.zip
        asset_name: UnityLive2DExtractor-${{ inputs.buildType }}-net8.0-win-x64.zip
        asset_content_type: application/zip