name: Build wxFormBuilder
on:
  workflow_dispatch:
    inputs:
      build_timestamp:
        description: 'Build Timestamp (UTC - YYYY-MM-DD HH:MM:SS)'
        required: true
        default: '2025-01-24 14:41:20'
      build_user:
        description: 'Builder Username'
        required: true
        default: 'neekaru'

env:
  BUILD_TIMESTAMP: ${{ github.event.inputs.build_timestamp }}
  BUILD_USER: ${{ github.event.inputs.build_user }}
  BUILD_VERSION: snapshot-${{ github.sha }}

jobs:
  source:
    name: Package Source
    runs-on: windows-latest
    outputs:
      version: ${{ env.BUILD_VERSION }}
    steps:
      - uses: actions/github-script@v7.0.1
        id: variables
        with:
          result-encoding: string
          script: |
            if (context.ref.startsWith('refs/tags/v')) {
              return context.ref.split('/').pop().slice(1);
            } else {
              return context.ref.split('/').pop();
            }

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: wxFormBuilder/wxFormBuilder
          path: target-repo
          submodules: recursive

      - name: Create source archive
        shell: cmd
        working-directory: target-repo
        run: |
          echo Build by ${{ env.BUILD_USER }} at ${{ env.BUILD_TIMESTAMP }} > build_info.txt
          7z a -tzip "..\wxFormBuilder-${{ env.BUILD_VERSION }}-source.zip" * -xr!.git*

      - uses: actions/upload-artifact@v4.4.3
        with:
          name: Source Package
          path: wxFormBuilder-*-source.zip

  build-32bit:
    needs: source
    name: Build 32-bit
    runs-on: windows-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: wxFormBuilder/wxFormBuilder
          path: target-repo
          submodules: recursive

      - uses: msys2/setup-msys2@v2.24.1
        with:
          msystem: mingw32
          release: false
          update: false
          install: >-
            mingw-w64-i686-toolchain
            mingw-w64-i686-cmake
            mingw-w64-i686-make
            mingw-w64-i686-wxWidgets3.2
            mingw-w64-i686-boost
            base-devel
            git

      - name: Build
        shell: msys2 {0}
        working-directory: target-repo
        run: |
          echo "Build by ${{ env.BUILD_USER }} at ${{ env.BUILD_TIMESTAMP }}" > build_info.txt
          cmake -S . -B _build -G "MSYS Makefiles" --install-prefix "$PWD/_install" -DCMAKE_BUILD_TYPE=Release
          cmake --build _build --config Release -j `nproc`
          cmake --install _build --config Release --strip
          cp build_info.txt _install/

      - name: Create archive
        shell: cmd
        working-directory: target-repo
        run: |
          cd _install
          7z a -tzip "..\\wxFormBuilder-${{ env.BUILD_VERSION }}-win32.zip" .

      - name: Create installer
        shell: cmd
        working-directory: target-repo
        run: |
          ISCC.exe /DArch=i686 /O. data\\packaging\\windows\\wxFormBuilder.iss

      - uses: actions/upload-artifact@v4.4.3
        with:
          name: Windows 32-bit
          path: |
            target-repo/wxFormBuilder-*-win32.zip
            target-repo/wxFormBuilder-*.exe

  build-64bit:
    needs: source
    name: Build 64-bit
    runs-on: windows-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: wxFormBuilder/wxFormBuilder
          path: target-repo
          submodules: recursive

      - uses: msys2/setup-msys2@v2.24.1
        with:
          msystem: ucrt64
          release: false
          update: false
          install: >-
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-make
            mingw-w64-ucrt-x86_64-wxWidgets3.2
            mingw-w64-ucrt-x86_64-boost
            base-devel
            git

      - name: Build
        shell: msys2 {0}
        working-directory: target-repo
        run: |
          echo "Build by ${{ env.BUILD_USER }} at ${{ env.BUILD_TIMESTAMP }}" > build_info.txt
          cmake -S . -B _build -G "MSYS Makefiles" --install-prefix "$PWD/_install" -DCMAKE_BUILD_TYPE=Release
          cmake --build _build --config Release -j `nproc`
          cmake --install _build --config Release --strip
          cp build_info.txt _install/

      - name: Create archive
        shell: cmd
        working-directory: target-repo
        run: |
          cd _install
          7z a -tzip -bb1 "..\\wxFormBuilder-${{ env.BUILD_VERSION }}-win64.zip" .

      - name: Create installer
        shell: cmd
        working-directory: target-repo
        run: |
          ISCC.exe /DArch=x86_64 /O. data\\packaging\\windows\\wxFormBuilder.iss

      - uses: actions/upload-artifact@v4.4.3
        with:
          name: Windows 64-bit
          path: |
            target-repo/wxFormBuilder-*-win64.zip
            target-repo/wxFormBuilder-*.exe

  release:
    needs: [source, build-32bit, build-64bit]
    name: Create Release
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4.4.3
        with:
          pattern: "*"
          merge-multiple: true

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: wxFormBuilder-*
          draft: true
          tag_name: snapshot.${{ env.BUILD_TIMESTAMP }}
          name: "wxFormBuilder Snapshot (Built by ${{ env.BUILD_USER }} at ${{ env.BUILD_TIMESTAMP }})"
          body: |
            Snapshot Build Information:
            - Built by: ${{ env.BUILD_USER }}
            - Build date: ${{ env.BUILD_TIMESTAMP }}
            - Build type: Release
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}